### ISSUE TITLE
Custom Randomizer

### ISSUE THREAD

**Issue by Stingerman06** [GateGuy/SimpleRandomizerMaker#1]
Using the latest randomizer and I'm just heavily unsure what's going on with it. Alternate alias is Chagmen. The problem only shows up on the 2nd option, "Randomize Characters per Track". No matter which option is selected with it(even nothing extra is selected), I just get the error "At least one of your rules is bad (has no possible solution).".

[randomizer.txt](https://github.com/Mips96/SimpleRandomizerMaker/files/7530645/randomizer.txt)

**Comment by Stingerman06** [comment]
I figured out what was wrong with it(somehow). There's a bug somewhere because I had to rename one of my Optional Rulesets along with the rest of the rules associated with it. ["Randomize Characters per Track"] was renamed entirely and that fixed that problem. At first I thought it was with the length of the name, then I checked any grammar related to word order, but I couldn't figure it out in the end.

**Comment by Stingerman06** [comment]
Update on this. I got another error when reorganizing my code around, and I figured out that the "Required_Rules" was the main thing causing the issue. I moved the respective rules to the rules[], section in one of the "Optional_Rules" rulesets and that completely fixed this issue. I have a feeling if I try to use "Required_Rules" in the future, something is gonna break again.

**Comment by Mode8fx** [comment]
**Short answer**: Your "Balance out special board Prices" rule is bad; change the < to a >.

**Long answer**: I found a few things from looking through your randomizer.
First, the less important findings: I don't think the name of a ruleset would be the issue (there aren't any length/grammar restrictions), and renaming "Randomize Characters per Track" didn't change anything on my end. Second, I got the same results regardless of whether the required rulesets were actually required or changed to be optional (while enabled).

The problem seems to be your "Balance out special board Prices" rule. This makes it so that Special Feather Price is always less than Special Star Price; however, the default Special Feather Price is greater than the default Special Star Price, so if you lock those prices (by not enabling the Randomize Board Prices ruleset), that rule will always fail. Changing the < to a > (so that Special Feather Price is always greater than Special Star Price) makes every combination of rulesets work.

**Comment by Stingerman06** [comment]
Actually, that would of destroyed the thing entirely. Feather is 80,000 at max and 2 at min and the star is 100,000 at max and 3 at min. It was in perfect logic that I force the feather board below the star board's price, since the max is the base price for those boards specifically, and I wanted to ensure the price doesn't go higher than the star board. With those in Required Rules, it was registering those values 100% fine, but would fail at writing the character values entirely(then brought the bad rules error, even though it had nothing to do with those rules). My randomizer works perfectly fine now(no errors) after I moved those out from Required Rules, and into the rules for Board Prices Optional_Ruleset. I haven't had issues with this since, and no values or operators were changed around either between my current file and that one I dropped here for checking.

Do you get the same errors if you moved those from "Required_Rules" to the "Optional_Ruleset", 'Randomize Board Prices'? Cause that completely fixed the entire issue for me.

**Comment by Mode8fx** [comment]
> Feather is 80,000 at max and 2 at min and the star is 100,000 at max and 3 at min.

You may want to double check that. According to the addresses in your posted file (and [a quick YouTube search](https://youtu.be/Ymp4dR2bclU?t=170); I've never actually played Snowboard Kids), the original prices are 100,000 for Feather and 80,000 for Star. It looks like you got those two addresses mixed up; swapping their attributes (just rename Special Feather Price to Special Star Price and vice-versa) without changing anything else fixes everything on my end.

The reason moving the required rules into "Randomize Board Prices" fixed the error is because the "invalid rule" issue was caused by the required rule that Special Feather (locked at 100,000) must cost less than Special Star (locked at 80,000), and the only wat that's possible is by either removing the required rule comparing them, or enabling "Randomize Board Prices" so that their values are unlocked.
